plugins {
    id 'com.android.application'
}

android {
    namespace 'it.affareradar.worker'
    compileSdk 35

    defaultConfig {
        applicationId 'it.affareradar.worker.note8worker3'
        minSdk 21
        targetSdk 28
        versionCode 1
        versionName '0.5-note8-worker'
    }
}
